name: flutter_space_shooter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.21.0
  flame_audio: ^1.2.0
  flutter_bloc: ^8.1.0 # For BLOC state management
  equatable: ^2.0.5 # Optional, helps with state comparison in BLOC

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/
    - assets/images/ships/
    - assets/images/bullets/
    - assets/images/effects/
    - assets/images/ui/
    - assets/images/ui/buttons/
    - assets/audio/sounds/
    - assets/audio/musics/

  fonts:
    - family: GoodTiming
      fonts:
        - asset: fonts/good_timing.otf
    - family: FragileBombers
      fonts:
        - asset: fonts/fragile_bombers.otf
